#pragma once

#include <ftk2/core/feature.hpp>
#include <vector>

namespace ftk2 {

/**
 * @brief Represents the simplicial complex generated by the tracking engine.
 * 
 * Tracking is a transformation: Spacetime Mesh -> Feature Complex.
 */
struct FeatureComplex {
    // Vertices of the complex (FeatureElements found on m-simplices)
    std::vector<FeatureElement> vertices;

    // Connectivity of the complex (simplices of dimension 1..k)
    // For a 1D track, this stores edges (pairs of vertex indices).
    // For a 2D track, this stores faces (triplets of vertex indices).
    struct SimplexIndices {
        int dimension;
        std::vector<uint32_t> indices; 
    };
    std::vector<SimplexIndices> connectivity;

    /**
     * @brief Slices the complex at a specific time step.
     * This is a standard geometric intersection of the complex with t=T.
     */
    void slice(double t, std::vector<FeatureElement>& output) const;
};

} // namespace ftk2
