#pragma once

#include <ftk2/core/feature.hpp>
#include <vector>

namespace ftk2 {

/**
 * @brief Represents the simplicial complex generated by the tracking engine.
 * 
 * Tracking is a transformation: Spacetime Mesh -> Feature Complex.
 */
struct FeatureComplex {
    // Vertices of the complex (FeatureElements found on m-simplices)
    std::vector<FeatureElement> vertices;

    // Connectivity of the complex (simplices of dimension 1..k)
    // For a 1D track, this stores edges (pairs of vertex indices).
    // For a 2D track, this stores faces (triplets of vertex indices).
    struct SimplexIndices {
        int dimension;
        std::vector<uint32_t> indices; 
    };
    std::vector<SimplexIndices> connectivity;

    void sort() {
        // Sort the connectivity vector itself by dimension
        std::sort(connectivity.begin(), connectivity.end(), [](const SimplexIndices& a, const SimplexIndices& b) {
            return a.dimension < b.dimension;
        });

        for (auto& conn : connectivity) {
            int n = conn.dimension + 1;
            if (n <= 0) continue;
            std::vector<std::vector<uint32_t>> cells;
            for (size_t i = 0; i < conn.indices.size(); i += n) {
                if (i + n > conn.indices.size()) break;
                std::vector<uint32_t> cell(n);
                for (int j = 0; j < n; ++j) cell[j] = conn.indices[i + j];
                std::sort(cell.begin(), cell.end());
                cells.push_back(cell);
            }
            std::sort(cells.begin(), cells.end());
            cells.erase(std::unique(cells.begin(), cells.end()), cells.end());
            
            conn.indices.clear();
            conn.indices.reserve(cells.size() * n);
            for (const auto& cell : cells) {
                for (uint32_t idx : cell) conn.indices.push_back(idx);
            }
        }
    }

    /**
     * @brief Slices the complex at a specific time step.
     * This is a standard geometric intersection of the complex with t=T.
     */
    void slice(double t, std::vector<FeatureElement>& output) const;
};

} // namespace ftk2
