#pragma once

#include <vector>
#include <cstdint>
#include <functional>
#include <memory>

#ifdef __CUDACC__
#define FTK_HOST_DEVICE __host__ __device__
#else
#define FTK_HOST_DEVICE
#endif

namespace ftk2 {

/**
 * @brief Represents a K-dimensional simplex within a mesh.
 * 
 * A simplex is uniquely identified by its dimension and its vertices.
 */
struct Simplex {
    int dimension; // K
    uint64_t vertices[16]; // K+1 vertex IDs

    FTK_HOST_DEVICE int num_vertices() const { return dimension + 1; }
    
    bool operator==(const Simplex& other) const {
        if (dimension != other.dimension) return false;
        for (int i = 0; i <= dimension; ++i) {
            if (vertices[i] != other.vertices[i]) return false;
        }
        return true;
    }
};

/**
 * @brief A unified interface for simplicial meshes of any dimension.
 */
class Mesh {
public:
    virtual ~Mesh() = default;

    virtual int get_spatial_dimension() const = 0;
    virtual int get_total_dimension() const = 0;

    virtual void iterate_simplices(int k, std::function<void(const Simplex&)> callback) const = 0;

    virtual void faces(const Simplex& s, std::function<void(const Simplex&)> callback) const {
        for (int i = 0; i <= s.dimension; ++i) {
            Simplex f;
            f.dimension = s.dimension - 1;
            int k = 0;
            for (int j = 0; j <= s.dimension; ++j) {
                if (i == j) continue;
                f.vertices[k++] = s.vertices[j];
            }
            callback(f);
        }
    }

    virtual void cofaces(const Simplex& s, std::function<void(const Simplex&)> callback) const = 0;
    virtual std::vector<double> get_vertex_coordinates(uint64_t vertex_id) const = 0;
};

/**
 * @brief Spacetime mesh generated by extruding a simplicial mesh.
 * 
 * This class can be applied recursively to extrude multiple dimensions.
 * Example: 2D Mesh -> 3D Volume -> 4D Spacetime
 */
class ExtrudedSimplicialMesh : public Mesh {
public:
    ExtrudedSimplicialMesh(std::shared_ptr<Mesh> base_mesh, uint64_t n_layers = 0) 
        : base_mesh_(base_mesh), n_layers_(n_layers) {}

    int get_spatial_dimension() const override { return base_mesh_->get_spatial_dimension(); }
    int get_total_dimension() const override { return base_mesh_->get_total_dimension() + 1; }

    void iterate_simplices(int k, std::function<void(const Simplex&)> callback) const override {
        // Implementation for recursive extrusion
    }

    void cofaces(const Simplex& s, std::function<void(const Simplex&)> callback) const override {
        // Implementation for coface discovery in extruded mesh
    }

    std::vector<double> get_vertex_coordinates(uint64_t vertex_id) const override {
        return {};
    }

private:
    std::shared_ptr<Mesh> base_mesh_;
    uint64_t n_layers_;
};

/**
 * @brief Spacetime mesh where the geometry deforms between layers.
 * 
 * Vertex coordinates can change at each layer (e.g., following a flow).
 */
class DeformedExtrudedSimplicialMesh : public Mesh {
public:
    DeformedExtrudedSimplicialMesh(std::shared_ptr<Mesh> base_mesh, uint64_t n_layers = 0)
        : base_mesh_(base_mesh), n_layers_(n_layers) {}

    int get_spatial_dimension() const override { return base_mesh_->get_spatial_dimension(); }
    int get_total_dimension() const override { return base_mesh_->get_total_dimension() + 1; }

    void iterate_simplices(int k, std::function<void(const Simplex&)> callback) const override {
        // Topology is same as ExtrudedSimplicialMesh
    }

    void cofaces(const Simplex& s, std::function<void(const Simplex&)> callback) const override {
        // Topology is same as ExtrudedSimplicialMesh
    }

    std::vector<double> get_vertex_coordinates(uint64_t vertex_id) const override {
        // Returns deformed coordinates
        return {};
    }

private:
    std::shared_ptr<Mesh> base_mesh_;
    uint64_t n_layers_;
};

/**
 * @brief Factory for creating unified mesh objects.
 */
class MeshFactory {
public:
    static std::unique_ptr<Mesh> create_regular_mesh(const std::vector<uint64_t>& spatial_dims);
    static std::unique_ptr<Mesh> create_extruded_mesh(std::shared_ptr<Mesh> base_mesh, uint64_t n_layers = 0);
};

} // namespace ftk2
